all: boot merger i386 ia32

boot:
	@echo
	@echo start build boot loader

	make -C "./boot"

merger:
	@echo start build merger
	
	make -C "./merger"

i386:
	@echo 
	@echo start build i386

	make -C "./i386"

ia32:
	@echo 
	@echo start build ia32

	make -C "./ia32"